SELECT oh.ORGANIZATION_ID, oh.INVENTORY_ITEM_ID, im.SEGMENT1 AS PartNumber, oh.Qty AS OnHandQty
FROM ptq_OnHand_Sum AS oh LEFT JOIN ptq_ItemMap AS im ON (oh.INVENTORY_ITEM_ID = im.INVENTORY_ITEM_ID) AND (oh.ORGANIZATION_ID = im.ORGANIZATION_ID);

